apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-form
spec:
  replicas: 3 # Number of pod replicas in the ReplicaSet
  selector:
    matchLabels:
      app: form
  template:
    metadata:
      labels:
        app: form
    spec:
      containers:
        - name: php
          image: chiragg619/my-php-website # Ensure this image is available
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: form
spec:
  selector:
    app: form
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
